# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "iOS Certificates"
  lane :certificates do
    match(app_identifier: 'com.whenly', type: 'development', readonly: true)
    match(app_identifier: 'com.whenly', type: 'appstore', readonly: true)
  end

  desc "Push a new development build to TestFlight - QA"
  lane :testFlight do
      # Register Devices for Ad-hoc Testing
      # register_devices(devices_file: "./devices.txt")
      
      # disable automatic code signing
      # disable_automatic_code_signing

      # Check Certificates
      match(
        type: "appstore",
        app_identifier: "com.whenly",
        force_for_new_devices: true,
        readonly: is_ci
      )

      # Changelog
      changelog = prompt(
        text: "What's new on this build? (type END to submit): ",
        multi_line_end_keyword: "END"
      )

      clear_derived_data

      # Update build number
      increment_build_number

     
      # Build
      build_app(
        scheme: "Whenly",
        export_method: "app-store",
        # include_bitcode: true,
      )

      # Upload TestFlight
      upload_to_testflight(
        skip_waiting_for_build_processing: true,
        notify_external_testers: false,
        itc_provider: '3934GD6Y3P'
      )

      # Clean
      # clean_build_artifacts
  end
end
